### ISSUE TITLE
Archiv this fork

### ISSUE THREAD

**Issue by Falke-Design** [Leaflet/Leaflet.Graticule#10]
@IvanSanchez it looks like the intention of this fork was, to make the plugin with Leaflet v1.x compatible but this is now solved by the master repo. So I think the users should use the original one.

Sample with Leaflet 1.7.1 and the latest release from cloudybay: https://plnkr.co/edit/DHw9dG85V5iI7Epg

The only difference that I noticed was, that the repo from Leaflet organisation is available in CDN [jsdelivr](https://www.jsdelivr.com/?query=Leaflet.Gradicule)

**Comment by IvanSanchez** [comment]
Yeah, looks like upstream has been getting updates. Will archive.
